AWSTemplateFormatVersion: 2010-09-09
Description: cicd_handson
Parameters:
  PjName:
    Type: String
    Default: cicdhandson
Resources:
  CICDHandsonRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Sub "${PjName} CodeCommit Repositroy"
      RepositoryName: !Sub "${PjName}"
      Tags:
        - Key: Name
          Value: !Sub "${PjName}"

Outputs:
  CodeCommitRepositoryName:
    Value: !GetAtt "CICDHandsonRepository.Name"
    Export:
      Name: CodeRepositoryName
  CodeCommitRepositoryArn:
    Value: !GetAtt CICDHandsonRepository.Arn
    Export:
      Name: CodeRepositoryArn
  CodeCommitRepositoryUrl:
    Value: !GetAtt CICDHandsonRepository.CloneUrlHttp
    Export:
      Name: CodeRepositoryUrl
